version: '3'
services:
  article-api:
    build: ./node-postgres
    working_dir: /app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./node-postgres:/app
      - /app/node_modules
  postgres:
    build: ./node-postgres/postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqoin
    working_dir: /app
    volumes:
      - ./python-mysql:/app
      - ./python-mysql/mariadb:/docker-entrypoint-initdb.d
      - ./python-mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    command:  mysqld
  python:
    build: ./python-mysql
    volumes:
      - ./python-mysql:/app
    command: /app/wait.sh
    ports:
      - "8081:8080"
  article-api-fassade:
    build: ./node-queries-filter
    ports:
      - "9091:3000"
    working_dir: /app
    volumes:
      - ./node-queries-filter:/app
      - /app/node_modules
    command: node index.js
  article-auth:
    build: ./node-auth
    working_dir: /app
    volumes:
      - ./node-auth:/app
      - /app/node_modules
    command: node index.js
  